require_relative '../node_modules/react-native/scripts/react_native_pods'

ENV['RCT_NEW_ARCH_ENABLED'] = '0'

platform :ios, '16.0'
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'PrivacyProtectExample' do
  # Temporarily disable autolinking to avoid the error
  # config = use_native_modules!

  use_react_native!(
    :path => "../node_modules/react-native",
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'PrivacyProtect', :path => "../../"

  post_install do |installer|
    react_native_post_install(
      installer,
      "../node_modules/react-native",
      :mac_catalyst_enabled => false,
    )
  end
end